version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm test
workflows:
    build-and-test:
      jobs:
        - build-and-test

# version: 2
# jobs:
#   build:
#     docker:
#       - image: circleci/node:7.9-browsers
#     steps:
#       - checkout
#       - run:
#           name: Update npm
#           command: 'sudo npm install -g npm@latest'
#       - restore_cache:
#           key: dependency-cache-{{ checksum "package-lock.json" }}
#       - run:
#           name: Install npm wee
#           command: npm install && npm run build
#       - save_cache:
#           key: dependency-cache-{{ checksum "package-lock.json" }}
#           paths:
#             - node_modules
#   test:
#     docker:
#       - image: circleci/node:7.9-browsers
#     steps:
#       - checkout
#       - run:
#           name: Test
#           command: npm test
# workflows:
#   version: 2
#   build_and_test:
#     jobs:
#       - build
#       - test:
#           requires:
#             - build
#           filters:
#             branches:
#               only: master