{{- if .Values.ingress.enabled -}}
{{- $ingressPort := .Values.service.httpPort -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-patient-browser-ingress
  annotations:
    kubernetes.io/ingress.class: {{ .Values.ingress.class }}
spec:
  rules:
    - host: {{ .Values.ingress.host}}
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ .Release.Name }}-patient-browser
                port: 
                  number: {{ $ingressPort }}
{{- end }}