version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: NPM_CONFIG_PRODUCTION=false NODE_ENV=production npm install
            # - run: npm test
            - run: ./node_modules/karma/bin/karma start ./karma.conf.js --no-auto-watch --single-run --browsers Chrome
workflows:
    build-and-test:
      jobs:
        - build-and-test